version: '3'
services:
  app:
    image: nginx:latest
    container_name: react_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/var/www
    ports:
      - "9595:9595"
    privileged: true